let Addition = (Number1,Number2) => {
    return Number1+Number2;
    }
    
    console.log('Sum Result'+' ' + Addition(30,20) );

    let Subtraction  = (Number1,Number2) => {
        return Number1-Number2;
    }
        
    console.log('Sub Result'+' ' + Subtraction(30,20) );

    let Multiplication  = (Number1,Number2) => {
         return Number1*Number2;
    }         
    console.log('Mul Result'+' ' + Multiplication(30,20) );
            
    let Division = (Number1,Number2) => {
        return Number1/Number2;
    }
                
    console.log('Div Result'+' ' + Division(30,20) );

   
                /*
                const add = (num1, num2) => num1 + num2;
console.log('Sum Result: ' + add(30, 20));

const subtract = (num1, num2) => num1 - num2;
console.log('Sub Result: ' + subtract(30, 20));

const multiply = (num1, num2) => num1 * num2;
console.log('Mul Result: ' + multiply(30, 20));

const divide = (num1, num2) => num1 / num2;
console.log('Div Result: ' + divide(30, 20));
*/