let value1 = '1';
let value2 = '1';
let value3 = '2';
let value4 = true;
let value5 = 1;
let value6 ;
/*
if (value1 == value2){
console.log('Matched');
}else{
console.log('Not Matched');
}

if (value1==value3) {
console.log('Matched');
} else {
console.log('Not Matched');
}
if (value4) {
console.log('Matched');
} else {
console.log('Not Matched');
}*/

if (value1 == value5) {
    console.log('Matched');
}else {
    console.log('Not-Matched');
}

if (value1 === value5) {
    console.log('Matched');
}else {
    console.log('Not-Matched');
}
if (value1) {
    console.log('Matched');
} else {
    console.log('Not Matched');
 }